import Head from "next/head";

import {UserProvider} from "../context/UserContext";
import Login from "../components/Login";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <UserProvider>
        <Login />
      </UserProvider>
    </div>
  );
}
